
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5444:5432
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - my_redis_data:/data

networks:
  app_network:
    driver: bridge

volumes:
  my_postgres_data:
  my_redis_data:
